# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# clear_all_shortcuts yes
map ctrl+shift+left no_op
map ctrl+shift+right no_op

bold_font auto
italic_font auto
bold_italic_font auto

copy_on_select yes

window_padding_width 4

allow_hyperlinks yes
allow_remote_control yes
editor /usr/bin/nvim

macos_titlebar_color dark
shell_integration disabled
dynamic_title no
cursor_shape block
macos_menubar_title_max_length 0
macos_show_window_title_in none

enabled_layouts splits,stack

map cmd+plus change_font_size all +1.0
map cmd+equal change_font_size all +1.0
map cmd+minus change_font_size all -1.0

map cmd+j send_key alt+j
map cmd+k send_key alt+k
map cmd+o send_key alt+o

macos_option_as_alt both

map cmd+v paste_from_clipboard
map cmd+м paste_from_clipboard

map alt+v paste_from_clipboard
map alt+м paste_from_clipboard
 
# map ctrl+t>c new_tab_with_cwd
# map ctrl+t>, set_tab_title
#
# map ctrl+t>% launch --location=vsplit --cwd=current
# map ctrl+t>" launch --location=hsplit --cwd=current
#
# map ctrl+t>h neighboring_window left
# map ctrl+t>j neighboring_window down
# map ctrl+t>k neighboring_window up
#
# map ctrl+t>n next_tab
# map ctrl+t>p previous_tab
# map ctrl+t>l goto_tab -1
#
# map ctrl+t>1 goto_tab 1
# map ctrl+t>2 goto_tab 2
# map ctrl+t>3 goto_tab 3
# map ctrl+t>4 goto_tab 4
# map ctrl+t>5 goto_tab 5
# map ctrl+t>6 goto_tab 6
# map ctrl+t>7 goto_tab 7
# map ctrl+t>8 goto_tab 8
# map ctrl+t>9 goto_tab 9
#
# map ctrl+t>x close_window
#
# map ctrl+t>z toggle_fullscreen
