[ids]
*

[main]
# Привязываем клавишу Caps Lock к нашему кастомному слою
leftalt = leftmeta
leftmeta = leftalt
capslock = layer(my_ctrl_layer)

# Создаем слой my_ctrl_layer, который полностью наследует поведение Control (:C)
[my_ctrl_layer:C]
h = left
j = down
k = up
l = right
[ = esc
х = esc
